"""
PDF Exporter for Nyayadarsi
Generates court-admissible PDF audit reports using ReportLab.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from datetime import datetime, timezone
import io


BRAND_COLOR = HexColor("#1a237e")
ACCENT_COLOR = HexColor("#ff6f00")


def generate_audit_pdf(entity_id: str, audit_trail: list, tender_info: dict = None) -> bytes:
    """Generate a court-admissible PDF with full audit chain."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle('NyayaTitle', parent=styles['Title'],
                                  textColor=BRAND_COLOR, fontSize=20)
    header_style = ParagraphStyle('NyayaHeader', parent=styles['Heading2'],
                                   textColor=BRAND_COLOR)

    story = []

    # Header
    story.append(Paragraph("NYAYADARSI — AUDIT TRAIL REPORT", title_style))
    story.append(Paragraph("न्यायदर्शी — AI-Powered Procurement Accountability", styles['Normal']))
    story.append(Spacer(1, 10*mm))

    # Meta
    story.append(Paragraph(f"Entity ID: {entity_id}", styles['Normal']))
    generated = datetime.now(timezone.utc).isoformat()
    story.append(Paragraph(f"Generated: {generated}", styles['Normal']))
    story.append(Spacer(1, 5*mm))

    if tender_info:
        story.append(Paragraph("TENDER INFORMATION", header_style))
        for k, v in tender_info.items():
            story.append(Paragraph(f"<b>{k}:</b> {v}", styles['Normal']))
        story.append(Spacer(1, 5*mm))

    # Audit entries
    story.append(Paragraph("AUDIT CHAIN", header_style))
    story.append(Spacer(1, 3*mm))

    for i, entry in enumerate(audit_trail):
        story.append(Paragraph(f"<b>Entry #{i+1}</b>", styles['Heading4']))
        fields = [
            ("Timestamp", entry.get("timestamp", "N/A")),
            ("Action", entry.get("action", "N/A")),
            ("SHA-256 Input", entry.get("sha256_input", "N/A")),
            ("SHA-256 Output", entry.get("sha256_output", "N/A")),
            ("Model Version", entry.get("model_version", "N/A")),
            ("Officer ID", entry.get("officer_id", "N/A")),
            ("Verdict", entry.get("verdict", "N/A")),
            ("Confidence", str(entry.get("confidence", "N/A"))),
        ]
        for label, value in fields:
            story.append(Paragraph(f"<b>{label}:</b> {value}", styles['Normal']))
        story.append(Spacer(1, 3*mm))

    # Footer note
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph(
        "This document is generated by Nyayadarsi. All SHA-256 hashes can be independently verified. "
        "This report is intended for use as evidence in proceedings before the Central Administrative Tribunal "
        "or jurisdictional High Court under Article 226 of the Constitution of India.",
        styles['Normal']
    ))

    doc.build(story)
    return buffer.getvalue()
